package dev.controller.dto;

public enum ErrorCode {
	ID_INVALID, JSON_PARSE, SERVICE, INVALID_NAME, INVALID_FACTURATION, INVALID_POURCENTAGE, ALLREADY_EXISTS, TO_SHORT_DATE, INVALID_DATE, INVALID_ID_MISSION, FILE_ERROR, NO_PRIME, DELETE_IMPOSSIBLE
}